name: Mindful News Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_pipeline:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:

      # 1. Checkout the code (full history required for merge)
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # 2. Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      # 3. Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 4. Generate RSS
      - name: Generate RSS
        run: python main.py

      # 5. Validate the newly generated RSS
      - name: Validate RSS (main output)
        run: python validate_rss.py docs/mindfulnews.xml

      # 6. Commit & push updated RSS back to the repo (merge remote changes first)
      - name: Commit updated RSS
        uses: EndBug/add-and-commit@v9
        with:
          add: docs/mindfulnews.xml
          message: "chore: update mindfulnews.xml [skip ci]"
          pull: true
          push: true

      # 7. Run editorial filter
      - name: Run editorial filter
        run: python editorial_filter.py docs/mindfulnews.xml docs/mindfulnews_filtered.xml

      # 8. Validate the filtered RSS
      - name: Validate RSS (filtered output)
        run: python validate_rss.py docs/mindfulnews_filtered.xml

      # 9. Commit & push the filtered RSS as well (merge remote changes first)
      - name: Commit filtered RSS
        uses: EndBug/add-and-commit@v9
        with:
          add: docs/mindfulnews_filtered.xml
          message: "chore: update mindfulnews_filtered.xml [skip ci]"
          pull: true
          push: true

      # 10. Upload filtered RSS as an artifact
      - name: Upload filtered RSS as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mindfulnews_filtered
          path: docs/mindfulnews_filtered.xml

      # 11. Notify success
      - name: Notify success
        run: echo "Mindful News pipeline completed successfully!"