# .github/workflows/run.yml

name: Run Mindful News Aggregator

on:
  schedule:
    # Run every 2 hours
    - cron: '0 */2 * * *'
  workflow_dispatch: # allows you to run manually from GitHub Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run mindfulnews script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python main.py

    - name: Upload RSS feed as artifact
      uses: actions/upload-artifact@v3
      with:
        name: mindfulnews.xml
        path: mindfulnews.xml
